# Generated by Django 5.2 on 2025-04-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('aim', models.TextField()),
                ('image', models.CharField(max_length=200)),
                ('progress_value', models.IntegerField()),
                ('direction', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
